# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: |
        apt update
        apt install docker docker-compose-plugin build-essential

    - name: Build
      run: go build -v ./...

    - name: Build WASM Container
    - run: out/c2w ubuntu:24.04 ./container.wasm

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
    
    - name: Test
      run: go test -v ./...
